language: java
jdk:
    - openjdk7
    - oraclejdk8
before_install:
    - cp ./etc/settings.xml ~/.m2/
    - cp ./etc/onFailure.sh  ~/
    - cp ./etc/onSuccess.sh  ~/
    - chmod 777 ~/onFailure.sh
    - chmod 777 ~/onSuccess.sh
script:
    - mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
    - mvn -B cobertura:cobertura coveralls:report
